-- Create Tables payments Schema Start***
-- OneToMany with Transaction table
CREATE TABLE payments.`Payment_Method` (
    `ID` INT NOT NULL,
    `NAME` VARCHAR(500) NOT NULL,
    `STATUS` INT DEFAULT 1,
    `CREATION_DATE` TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),

    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- OneToMany with Transaction table
CREATE TABLE payments.`Payment_Type` (
    `ID` INT NOT NULL,
    `TYPE` VARCHAR(500) NOT NULL,
    `STATUS` INT DEFAULT 1,
    `CREATION_DATE` TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),

    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- OneToMany with Transaction table
CREATE TABLE payments.`Provider` (
    `ID` INT NOT NULL,
    `PROVIDER_NAME` VARCHAR(2000) NOT NULL,
    `STATUS` INT DEFAULT 1,
    `CREATION_DATE` TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),

    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- OneToMany with Transaction table
CREATE TABLE payments.`Transaction_Status` (
    `ID` INT NOT NULL,
    `NAME` VARCHAR(2000) NOT NULL,
    `STATUS` INT DEFAULT 1,
    `CREATION_DATE` TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),

    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Parent table
CREATE TABLE payments.`Transaction` (
    `TXN_ID` VARCHAR(36) NOT NULL,
    `USER_ID` INT NOT NULL,
    `PAYMENT_METHOD_ID` INT NOT NULL,
    `PROVIDER_ID` INT NOT NULL,
    `PAYMENT_TYPE_ID` INT NOT NULL,
    `TXN_STATUS_ID` INT NOT NULL,
    `AMOUNT` DECIMAL(19,2) DEFAULT 0.00,
    `CURRENCY` VARCHAR(3) NOT NULL,
    `MERC_TXN_REF` VARCHAR(50) NOT NULL,
    `TXN_REF` VARCHAR(50) NOT NULL,
    `PROVIDER_REF` VARCHAR(100) DEFAULT NULL,
    `PROVIDER_CODE` VARCHAR(500) DEFAULT NULL,
    `PROVIDER_MESSAGE` VARCHAR(1000) DEFAULT NULL,
    `CREATION_DATE` TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),
    `UPDATED_DATE` TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),
    `RETRY_COUNT` INT DEFAULT 0,

    PRIMARY KEY (`TXN_ID`),

    UNIQUE KEY `transaction_txnReference` (`TXN_REF`),

    KEY `transaction_paymentMethodId` (`PAYMENT_METHOD_ID`),
    KEY `transaction_providerId` (`PROVIDER_ID`),
    KEY `transaction_txnStatusId` (`TXN_STATUS_ID`),
    KEY `transaction_paymentTypeId` (`PAYMENT_TYPE_ID`),

    CONSTRAINT `transaction_paymentMethodId`
        FOREIGN KEY (`PAYMENT_METHOD_ID`)
        REFERENCES `Payment_Method` (`id`),

    CONSTRAINT `transaction_providerId`
        FOREIGN KEY (`PROVIDER_ID`)
        REFERENCES `Provider` (`id`),

    CONSTRAINT `transaction_txnStatusId`
        FOREIGN KEY (`TXN_STATUS_ID`)
        REFERENCES `Transaction_Status` (`id`),

    CONSTRAINT `transaction_paymentTypeId`
        FOREIGN KEY (`PAYMENT_TYPE_ID`)
        REFERENCES `Payment_Type` (`id`)
);

-- OneToMany Transaction -> Transaction_Log
CREATE TABLE payments.`Transaction_Log` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `TXN_ID` VARCHAR(36) NOT NULL,
    `TXN_FROM_STATUS` VARCHAR(50) DEFAULT '-1',
    `TXN_TO_STATUS` VARCHAR(50) DEFAULT '-1',
    `CREATION_DATE` TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),
    PRIMARY KEY (`ID`),
    KEY `IDX_TRANSACTION_LOG_TXN_ID` (`TXN_ID`),
    CONSTRAINT `FK_TRANSACTION_LOG_TRANSACTION`
        FOREIGN KEY (`TXN_ID`)
        REFERENCES `Transaction` (`TXN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Create Tables payments Schema End***